import Core
import Utils
import XCTest

extension Diagnostic {

  /// A test annotation that announces `self` should be expected.
  fileprivate var expectation: TestAnnotation {
    TestAnnotation(
      in: site.file.url,
      atLine: site.first().line.number,
      parsing: "diagnostic " + message
    )
  }

}

extension XCTestCase {

  /// The effects of running the `processAndCheck` parameter to `checkAnnotatedValFiles`.
  fileprivate typealias ProcessingEffects = (
    /// Test failures generated by processing.
    testFailures: [XCTIssue],
    /// Val diagnostics generated by processing.
    diagnostics: DiagnosticSet
  )

  /// Applies `processAndCheck` to `valToTest` and the subset of its annotations whose commands
  /// match `checkedCommands`, recording resulting XCTest failures along with any additional
  /// failures where the effects of processing don't match the its annotation commands ("//!
  /// ... diagnostic ...").
  ///
  /// - Parameters:
  ///   - checkedCommands: the annnotation commands to be validated by `processAndCheck`.
  ///   - processAndCheck: applies some compilation phases to `file`, updating `diagnostics`
  ///     with any generated diagnostics, then checks `annotationsToCheck` against the results,
  ///     returning corresponding test failures. Throws an `Error` if any phases failed.
  fileprivate func checkAnnotations(
    in valToTest: SourceFile,
    checkingAnnotationCommands checkedCommands: Set<String> = [],
    _ processAndCheck: (
      _ file: SourceFile,
      _ annotationsToCheck: ArraySlice<TestAnnotation>,
      _ diagnostics: inout DiagnosticSet
    ) throws -> [XCTIssue]
  ) -> Bool {
    var annotations = TestAnnotation.parseAll(from: valToTest)

    // Separate the annotations to be checked by default diagnostic annotation checking from
    // those to be checked by `processAndCheck`.
    let p = annotations.partition(by: { checkedCommands.contains($0.command) })
    let (diagnosticAnnotations, processingAnnotations) = (annotations[..<p], annotations[p...])

    var diagnostics = DiagnosticSet()
    var processingThrewError = false

    let failures = XCTContext.runActivity(
      named: valToTest.baseName,
      block: { activity in
        let completedProcessingTestFailures = try? processAndCheck(
          valToTest, processingAnnotations, &diagnostics)

        processingThrewError = completedProcessingTestFailures == nil

        return failuresToReport(
          effectsOfProcessing: (
            testFailures: completedProcessingTestFailures ?? [],
            diagnostics: diagnostics
          ),
          unhandledAnnotations: diagnosticAnnotations)
      })

    for f in failures {
      record(f)
    }

    return !processingThrewError
  }

  /// Applies `process` to the ".val" file at the given path and reports XCTest failures where the
  /// effects of processing don't match the file's annotation commands ("//! ... diagnostic ...").
  ///
  /// - Parameter process: applies some processing to `file`, updating `diagnostics`
  ///   with any generated diagnostics. Throws an `Error` if processing failed.
  /// - Parameter expectSuccess: true if an error from `process` represents a test failure, false if
  ///   the lack of an error represents a test failure; nil if that information is to be derived
  ///   from the contents of the file.
  public func checkAnnotatedValFileDiagnostics(
    inFileAt valFilePath: String,
    expectSuccess: Bool,
    _ process: (_ file: SourceFile, _ diagnostics: inout DiagnosticSet) throws -> Void
  ) throws {
    let f = try SourceFile(at: valFilePath)

    // FIXME: clarify/explain this code
    let processingSucceeded = checkAnnotations(in: f, checkingAnnotationCommands: []) {
      (f, annotationsToHandle, diagnostics) in
      assert(annotationsToHandle.isEmpty)
      try process(f, &diagnostics)
      return []
    }

    if processingSucceeded != expectSuccess {
      record(
        XCTIssue(
          Diagnostic.error(
            processingSucceeded
              ? "processing succeeded, but failure was expected"
              : "processing failed, but success was expected",
            at: f.wholeRange)))
    }
  }

  /// Given the effects of processing, the annotations not specifically handled by `processAndCheck`
  /// above, returns the final set of test failures to be reported to XCTest.
  fileprivate func failuresToReport(
    effectsOfProcessing processing: ProcessingEffects,
    unhandledAnnotations: ArraySlice<TestAnnotation>
  ) -> [XCTIssue] {
    var testFailures = processing.testFailures

    var diagnosticsByExpectation = Dictionary(
      grouping: processing.diagnostics.elements, by: \.expectation)

    func fail(_ expectation: TestAnnotation, _ message: String) {
      testFailures.append(expectation.failure(message))
    }

    for a in unhandledAnnotations {
      switch a.command {
      case "diagnostic":
        if diagnosticsByExpectation[a]?.popLast() != nil {
        } else {
          fail(a, "missing expected diagnostic\(a.argument.map({": '\($0)'"}) ?? "")")
        }
      case "expect-failure": do {}
      case "expect-success": do {}
      default:
        fail(a, "unexpected test command: '\(a.command)'")
      }
    }

    testFailures += diagnosticsByExpectation.values.joined().lazy.map {
      XCTIssue(.error("unexpected diagnostic: '\($0.message)'", at: $0.site, notes: $0.notes))
    }
    return testFailures
  }

}
